### ISSUE TITLE
Loose the restrictions about image size  in  qjpegxlhandler

### ISSUE THREAD

**Issue by Huangzhiqiang** [novomesk/qt-avif-image-plugin#11]
Hello,
please increase the size restrictions such as 32768 in  qjpegxlhandler. The jpeg xl support much bigger size.   Thanks  :)

**Comment by novomesk** [comment]
It is necessary to have some practical/reasonable limit. Memory consumption grows quickly with large dimensions.

However, you can send me some real examples of big-dimensional AVIF images and I can see if/how can I adjust the limits.

**Comment by Huangzhiqiang** [comment]
Thanks for quick reply.  The restrictions for avif is reasonable. What I wanted to say was jpeg xl.

The dimensions of jxl can be up to 1073741823x1073741823 according to https://cloudinary.com/blog/time_for_next_gen_codecs_to_dethrone_jpeg. The jxl in https://1drv.ms/u/s!Asjjkor7_GLli19Lajs06kCBwGat?e=7KS9h4 is 49255x4200. I think the limit 65535x65535 which used in jpeg may be a good choice.
