### ISSUE TITLE
How do I get it to work on yac reader windows 11?

### ISSUE THREAD

**Issue by rohitghali** [novomesk/qt-avif-image-plugin#12]
I tried everything. Placed the DLLsin 'C:\Program Files\YACReader\imageformats'. Tried with both read only and write DLLs. Still yac says comic not found upon opening CBZs with avif files. Please help.

**Comment by novomesk** [comment]
YACReader is made using Qt 6.3.1 but qavif.dll was built using Qt 5.15.2

DLL for Qt5 will not work in Qt6 application.

qavif.dll should be built with ideally same Qt version.

Try following DLL which was built with Qt 6.2.4, for me it worked when I put qavif.dll in `C:\Program Files\YACReader\imageformats\` folder.
[avif_plugin_for_Qt6_2_4.zip](https://github.com/novomesk/qt-avif-image-plugin/files/10185369/avif_plugin_for_Qt6_2_4.zip)

Verify properties of `Qt6Gui.dll` file in the future to see what Qt version the application uses.

**Comment by rohitghali** [comment]
> YACReader is made using Qt 6.3.1 but qavif.dll was built using Qt 5.15.2
> 
> DLL for Qt5 will not work in Qt6 application.
> 
> qavif.dll should be built with ideally same Qt version.
> 
> Try following DLL which was built with Qt 6.2.4, for me it worked when I put qavif.dll in `C:\Program Files\YACReader\imageformats\` folder. [avif_plugin_for_Qt6_2_4.zip](https://github.com/novomesk/qt-avif-image-plugin/files/10185369/avif_plugin_for_Qt6_2_4.zip)
> 
> Verify properties of `Qt6Gui.dll` file in the future to see what Qt version the application uses.

Worked like a charm. Thanks.
