### ISSUE TITLE
Draft a Release

### ISSUE THREAD

**Issue by diemmarkus** [novomesk/qt-avif-image-plugin#3]
could you please draft a release (i.e. 0.1)? This also creates a tarball which I can use for the flathub build.

thanks!

**Comment by novomesk** [comment]
I plan to do it this week.

**Comment by novomesk** [comment]
qt-avif-image-plugin-0.1.0 is available https://github.com/novomesk/qt-avif-image-plugin/releases/tag/v0.1.0

**Comment by diemmarkus** [comment]
Nice, thx!
