### ISSUE TITLE
Draft a Release

### ISSUE THREAD

**Issue by diemmarkus** [novomesk/qt-avif-image-plugin#5]
I now tested your appveyor built with nomacs and it works like a charm. Currently, I simply download the dll in [cmake](https://github.com/nomacs/nomacs/blob/edf192223e2f77d1d816afb475b7b8a0ec627af5/ImageLounge/cmake/WinBuildTarget.cmake#L123) assuming there will always be one named `qavif.dll`. 

If you could change the status of [0.2.0](https://github.com/novomesk/qt-avif-image-plugin/releases/tag/v0.2.0) from `pre-release` to `release` (or draft a new one), I could change the download to the generic `releases/latest/qavif.dll`.

thanks for contributing!

**Comment by novomesk** [comment]
I changed 0.2.0 to release.
I will keep adding the qavif.dll in the future too.
If you change appveyor environment in the future (compiler or newer Qt version), please let me know so I will change it too.

**Comment by diemmarkus** [comment]
thanks!
